language: php
sudo: false

matrix:
  fast_finish: true
  include:
    - php: "7.2"
    - php: "7.3"
    - php: "nightly"
    - php: "master"
  allow_failures:
    - php: "nightly"
    - php: "master"

install:
  - composer self-update
  - composer update

script:
  - vendor/bin/phpunit
  - vendor/bin/psalm
